### ISSUE TITLE
SocketException NamespaceChangeStreamListener

### ISSUE THREAD

**Issue by emushtaq** [mongodb/stitch-android-sdk#82]
Hello,

I am getting a SocketException with this error in the stack trace. Could you please help debug. 

Some details about the way I try to push data:
- Authentication with mongodb-stitch.xml
- Using sync to push data
- Snippet:
```
public static void pushToStitch(StitchAppClient client, RemoteMongoCollection collection, Document data) {
        try {
            Log.d(TAG, "Push to Stitch called for collection: " + collection.getNamespace().getCollectionName());
            Document document = new Document();
            Date timestamp = new Date();
            document.put("owner_id", client.getAuth().getUser().getId());
            document.put("data", data);
            document.put("timestamp", timestamp.getTime());
            document.put("timestampString", timestamp.toString());

            final Task<RemoteInsertOneResult> res = collection.sync().insertOne(document);
            res.addOnCompleteListener(new OnCompleteListener<RemoteInsertOneResult>() {
                @Override
                public void onComplete(@com.mongodb.lang.NonNull final Task<RemoteInsertOneResult> task) {
                    if (task.isSuccessful()) {
                        Log.d(TAG, "Added information to collection" + task.getResult().toString());
                    } else {
                        Log.e(TAG, "Error adding item", task.getException());
                    }
                }
            });
        } catch (Exception e){
            Log.e(TAG, "ERROR pushing to stitch." + e.getMessage());
        }
    }
```

And I create the remote mongo collection object with something like this:

```
RemoteMongoCollection remoteMongoCollection = _mongoClient.getDatabase(ATLAS_DATABASE).getCollection(Constants.ATLAS_COLLECTION_WEATHER);
            class DailyFeatUpdateListener implements ChangeEventListener<Document> {
                @Override
                public void onEvent(final BsonValue documentId, final ChangeEvent<Document> event) {
                    if (!event.hasUncommittedWrites()) {
                        // Custom actions can go here
                    }
                    // refresh the app view, etc.
                }
            }
            class DailyFeatErrorListener implements ErrorListener {
                @Override
                public void onError(BsonValue documentId, Exception error) {
                    Log.e(TAG, error.getLocalizedMessage());
                    Set<BsonValue> docsThatNeedToBeFixed = remoteMongoCollection.sync().getPausedDocumentIds();
                    Log.e(TAG, "Number of documents that need to be fixed:" + docsThatNeedToBeFixed.size());
                    for (BsonValue doc_id : docsThatNeedToBeFixed) {
                        // Add your logic to inform the user.
                        // When errors have been resolved, call
                        remoteMongoCollection.sync().resumeSyncForDocument(doc_id);
                    }
                    // refresh the app view, etc.
                }
            }


            remoteMongoCollection.sync().configure(
                    DefaultSyncConflictResolvers.remoteWins(),
                    new DailyFeatUpdateListener(),
                    new DailyFeatErrorListener());
```
This is the error I get:

```
NamespaceChangeStreamListener::stream ns=data.location exception on fetching next event: java.net.SocketException: Socket closed
    java.net.SocketException: Socket closed
        at com.android.org.conscrypt.NativeCrypto.SSL_read(Native Method)
        at com.android.org.conscrypt.NativeSsl.read(NativeSsl.java:399)
        at com.android.org.conscrypt.ConscryptFileDescriptorSocket$SSLInputStream.read(ConscryptFileDescriptorSocket.java:546)
        at okio.Okio$2.read(Okio.java:140)
        at okio.AsyncTimeout$2.read(AsyncTimeout.java:237)
        at okio.RealBufferedSource.request(RealBufferedSource.java:68)
        at okio.RealBufferedSource.require(RealBufferedSource.java:61)
        at okio.RealBufferedSource.readHexadecimalUnsignedLong(RealBufferedSource.java:304)
        at okhttp3.internal.http1.Http1Codec$ChunkedSource.readChunkSize(Http1Codec.java:469)
        at okhttp3.internal.http1.Http1Codec$ChunkedSource.read(Http1Codec.java:449)
        at okio.RealBufferedSource.read(RealBufferedSource.java:47)
        at okio.RealBufferedSource.exhausted(RealBufferedSource.java:57)
        at okio.InflaterSource.refill(InflaterSource.java:102)
        at okio.InflaterSource.read(InflaterSource.java:62)
        at okio.GzipSource.read(GzipSource.java:80)
        at okio.RealBufferedSource.indexOf(RealBufferedSource.java:355)
        at okio.RealBufferedSource.readUtf8LineStrict(RealBufferedSource.java:227)
        at okio.RealBufferedSource.readUtf8LineStrict(RealBufferedSource.java:221)
        at com.mongodb.stitch.core.internal.net.OkHttpEventStream.readLine(OkHttpEventStream.java:47)
        at com.mongodb.stitch.core.internal.net.EventStreamReader.processEvent(EventStreamReader.java:90)
        at com.mongodb.stitch.core.internal.net.OkHttpEventStream.nextEvent(OkHttpEventStream.java:38)
        at com.mongodb.stitch.core.internal.net.Stream.nextEvent(Stream.java:53)
        at com.mongodb.stitch.core.services.mongodb.remote.sync.internal.NamespaceChangeStreamListener.storeNextEvent(NamespaceChangeStreamListener.java:216)
        at com.mongodb.stitch.core.services.mongodb.remote.sync.internal.NamespaceChangeStreamRunner.run(NamespaceChangeStreamRunner.java:78)
        at java.lang.Thread.run(Thread.java:764)
```

Maybe I am doing somthing wrong. Can you help verify? thanks

**Comment by adamchel** [comment]
Hi @emushtaq , these socket exceptions that you are seeing are normal. The data synchronization system for the Stitch SDK keeps connections with the Stitch server open for long periods of time, and they may intermittently disconnect and reconnect when losing internet or when syncing/desyncing new documents. This disconnect and reconnect results in the exceptions you see in the log. In a future release, we will hide these errors.

**Comment by adamchel** [comment]
Please open a new issue if you run into any more issues! We'll be happy to help. I will keep this issue open until we get around to hiding these exception.

**Comment by emushtaq** [comment]
@adamchel : Ahh. OK. Thanks for the reply. 👍
