### ISSUE TITLE
Default app client has not yet been initialized/set

### ISSUE THREAD

**Issue by percula** [mongodb/stitch-android-sdk#85]
I have created a simple application to test out the features of mongo-mobile on Android with a local only database. I have followed the [mobile-android todo sample](https://github.com/mongodb/stitch-examples/tree/master/todo/android-mobile) closely, but am encountering this exception when first initializing the client:

Mongo Gradle Dependencies:
```
    implementation 'org.mongodb:stitch-android-sdk:4.1.0'
    implementation 'org.mongodb:stitch-android-services-mongodb-local:4.1.0'
```

Code:
```
        // Create the default Stitch Client
        val client = Stitch.getDefaultAppClient() // EXCEPTION HERE

        // Create a Client for MongoDB Mobile (initializing MongoDB Mobile)
        val mobileClient = client.getServiceClient(LocalMongoDbService.clientFactory)
```

Exception:
```
2018-12-20 10:30:23.353 5342-5342/com.test.mongodbmobile E/AndroidRuntime: 
FATAL EXCEPTION: main
    Process: com.test.mongodbmobile, PID: 5342
    java.lang.RuntimeException: Unable to start activity ComponentInfo{com.test.mongodbmobile/com.test.mongodbmobile.MainActivity}: java.lang.IllegalStateException: default app client has not yet been initialized/set
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2913)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3048)
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:78)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1808)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:193)
        at android.app.ActivityThread.main(ActivityThread.java:6669)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
     Caused by: java.lang.IllegalStateException: default app client has not yet been initialized/set
        at com.mongodb.stitch.android.core.Stitch.getDefaultAppClient(Stitch.java:93)
        at com.perculacreative.mongodbmobile.MainActivity.onCreate(MainActivity.kt:29)
        at android.app.Activity.performCreate(Activity.java:7136)
        at android.app.Activity.performCreate(Activity.java:7127)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1271)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2893)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3048) 
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:78) 
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108) 
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1808) 
        at android.os.Handler.dispatchMessage(Handler.java:106) 
        at android.os.Looper.loop(Looper.java:193) 
        at android.app.ActivityThread.main(ActivityThread.java:6669) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858) 
```

**Comment by adamchel** [comment]
Hi @percula 

That error is expected if you do not initialize a default app client. There are two ways to initialize the default app client.

1. By adding the following line in your `strings.xml` file (replacing `your-client-app-id` with your app's client app ID:
```xml
<string name="stitch_client_app_id">your-client-app-id</string>
```

2. By manually calling `initializeDefaultAppClient` when your app starts up:
```java
Stitch.initializeDefaultAppClient("your-client-app-id");
```

Let me know if this fixes your issue, and please open another issue if you have any other problems while using Stitch!

**Comment by adamchel** [comment]
I am closing this issue since it's been a while. Please feel free to re-open it or open a new issue if you have any further problems.
